name: Deploy
on:
    push:
        branches: master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Yeetcode Server
              uses: appleboy/ssh-action@v0.1.2
              with:
                  host: ${{ secrets.SSH_HOST }}
                  key: ${{ secrets.SSH_KEY }}
                  username: ${{ secrets.SSH_USERNAME }}

                  script: |
                      cd deployment/yeetcode-server
                      pm2 stop 0
                      git pull
                      npm install
                      npm run build
                      pm2 start ./build/index.js
                      echo 'Deployment successful to digital ocean'
